name: Autodev
on:
  push:
    branches-ignore:
      - dev
  pull_request:
    types: [labeled, unlabeled, closed]

jobs:
  autodev:
    name: Build Branch
    runs-on: ubuntu-latest
    steps:
      - name: Get App Token
        uses: tibdex/github-app-token@v1.8.0
        id: get_token
        with:
          app_id: ${{ vars.STAFFBASE_ACTIONS_APP_ID }}
          private_key: ${{ secrets.STAFFBASE_ACTIONS_PRIVATE_KEY }}
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ steps.get_token.outputs.token }}
          fetch-depth: 0

      - name: Autodev
        uses: Staffbase/autodev-action@v1.8.2
        with:
          token: ${{ steps.get_token.outputs.token }}
