name: Autodev
on:
  push:
    branches-ignore:
      - dev
  pull_request:
    types: [labeled, unlabeled, closed]

jobs:
  autodev:
    uses: Staffbase/gha-workflows/.github/workflows/template_autodev.yml@v1.14.0
    with:
      base: master
      comments: true
    secrets:
      token: ${{ secrets.DEV_PUSH_TOKEN }}