name: CI Tests
env:
  NODE_VERSION: 14
on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  executing-tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node.js Version
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@staffbase'

      - name: Install Yarn Dependencies
        working-directory:  samples/weather-forecast
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.STAFFBOT_NPM_READ }}

      - name: Run Build
        working-directory: samples/weather-forecast
        run: yarn build

      - name: Run Lint
        working-directory: samples/weather-forecast
        run: yarn lint

      - name: Run Type check
        working-directory: samples/weather-forecast
        run: yarn type-check

      - name: Run Tests
        working-directory: samples/weather-forecast
        run: yarn test
